spring:
  profiles:
    active: local
---
spring:
  kafka:
    template:
      default-topic: library-events
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093,localhost:9094
  config:
    activate:
      on-profile: local
---
spring:
  profiles: dev
  kafka:
    producer:
      bootstrap-servers: dev:9091    #(Broker address)
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.String.Serializer
---
spring:
  profiles: prod
  kafka:
    producer:
      bootstrap-servers: prod:9091    #(Broker address)
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.String.Serializer